# Generated by Django 4.1.2 on 2022-10-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dad_hub', '0003_blurb_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blurb',
            name='name',
        ),
    ]
