# Generated by Django 4.1.2 on 2022-10-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dad_hub', '0005_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='content',
            field=models.TextField(default=1, max_length=1000),
        ),
    ]
