# Generated by Django 4.1.2 on 2022-10-12 01:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dad_hub', '0007_alter_response_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='blurb',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='dad_hub.blurb'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=5)),
                ('children_age', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('bio', models.TextField(max_length=300)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
