# Generated by Django 4.1.2 on 2022-10-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dad_hub', '0008_alter_response_blurb_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': []},
        ),
    ]
