# Generated by Django 4.1.2 on 2022-10-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dad_hub', '0010_alter_profile_options_remove_profile_children_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
