# Generated by Django 4.1.2 on 2022-10-12 17:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dad_hub', '0013_alter_bio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
    ]
