# Generated by Django 4.1.2 on 2022-10-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dad_hub', '0014_alter_bio_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='image',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blurb',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
